import {
  DistributionType,
  FillMode,
  LoopShape,
  OrientationMode,
  StaggerSource,
  CollisionMode,
} from './state.js';

const N = 36;

function shot(az, pol, dist, x = 0, y = 0, z = 0) {
  return {
    lockFraming: true,
    syncFromOrbit: true,
    azimuthDeg: az,
    polarDeg: pol,
    distance: dist,
    targetX: x,
    targetY: y,
    targetZ: z,
  };
}

export const PRESETS = [
  {
    name: 'Circle Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.CIRCLE,
        count: N,
        loopUseRadius: true,
        radius: 7,
        loopWidth: 7,
        loopDepth: 7,
      },
      orientation: { mode: OrientationMode.TO_CENTER, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.15, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#0b0c10' },
      camera: shot(8, 42, 24, 0, 0.2, 0),
    },
  },
  {
    name: 'Square Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.SQUARE,
        count: N,
        loopUseRadius: false,
        loopWidth: 5.6,
        loopDepth: 5.6,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.2 },
      render: { background: '#101218' },
      camera: shot(28, 48, 22, 0, 0.15, 0),
    },
  },
  {
    name: 'Lozenge Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.DIAMOND,
        count: N,
        loopUseRadius: false,
        loopWidth: 8,
        loopDepth: 8,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.05 },
      render: { background: '#0c1014' },
      camera: shot(0, 46, 26, 0, 0.2, 0),
    },
  },
  {
    name: 'Hexagon Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.HEXAGON,
        count: N,
        loopUseRadius: false,
        loopWidth: 7.2,
        loopDepth: 7.2,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.1 },
      render: { background: '#0e1210' },
      camera: shot(0, 44, 24, 0, 0.15, 0),
    },
  },
  {
    name: 'Triangle Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.TRIANGLE,
        count: N,
        loopUseRadius: false,
        loopWidth: 9,
        loopDepth: 9,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.05 },
      render: { background: '#120e10' },
      camera: shot(18, 50, 26, 0, 0.2, 0.4),
    },
  },
  {
    name: 'Star Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.STAR,
        count: N,
        loopUseRadius: false,
        loopWidth: 8,
        loopDepth: 8,
        starPoints: 5,
        starInnerRatio: 0.42,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.08 },
      render: { background: '#0d0b12' },
      camera: shot(0, 40, 27, 0, 0.15, 0),
    },
  },
  {
    name: 'Stacked Card Spiral',
    state: {
      object: { type: 'card' },
      card: {
        width: 1.586,
        height: 1.0,
        thickness: 0.03,
        cornerRadius: 0.06,
        segments: 6,
      },
      distribution: {
        type: DistributionType.COLUMN,
        columnAxis: 'y',
        columnCentered: false,
        columnCount: 30,
        columnSpacing: 0.038,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 260, falloff: 1.0, direction: 1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 5.6, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#0b0c10' },
      camera: shot(34, 66, 16, 0, 3.1, 0.4),
    },
  },
  {
    name: 'Icon Spiral Stack',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.COLUMN,
        columnAxis: 'y',
        columnCentered: false,
        columnCount: 18,
        columnSpacing: 0.16,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 300, falloff: 1.0, direction: 1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 4.5, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#f4f4f5' },
      camera: shot(34, 64, 19, 0.3, 6.2, 0.5),
    },
  },
  {
    name: 'Icon Carousel',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.CAROUSEL,
        carouselCount: 14,
        carouselRadius: 5.5,
        carouselY: 0,
        carouselFaceOut: true,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.2, positionX: 0, positionY: 1.1, positionZ: 0 },
      render: { background: '#0f1115' },
      camera: shot(12, 50, 28, 0, 1.3, 0),
    },
  },
  {
    name: 'Icon Coverflow',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.COVERFLOW,
        coverflowCount: 11,
        coverflowRadius: 7,
        coverflowSpreadDeg: 105,
      },
      orientation: { mode: OrientationMode.SHAPE_NORMAL, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.4, positionX: 0, positionY: 1.2, positionZ: 0 },
      render: { background: '#e8eef8' },
      camera: shot(0, 64, 20, 0, 1.35, 1.6),
    },
  },
  {
    name: 'Icon Fan Deck',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.15, thickness: 0.1, cornerRadius: 0.18, segments: 8 },
      distribution: {
        type: DistributionType.FAN,
        fanCount: 9,
        fanSpacing: 0.72,
        fanDepth: 0.22,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.U, amountDeg: 18, falloff: 1.0 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 3.0, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#8a8a8a' },
      camera: shot(0, 72, 22, 0, 0.1, 0.8),
    },
  },
  {
    name: 'Icon Diagonal Shelf',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 10,
        rowSpacing: 1.45,
        rowAngleDeg: 32,
        rowTiltDeg: 8,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: -14 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 12, falloff: 1.0 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.6, positionX: 0, positionY: 1.3, positionZ: 0 },
      render: { background: '#dce3f2' },
      camera: shot(-32, 54, 26, 0, 1.5, 0),
    },
  },
  {
    name: 'Icon Wave Parade',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.WAVE_ROW,
        rowCount: 14,
        rowSpacing: 1.35,
        waveAmplitude: 0.85,
        waveLength: 1.25,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.SINE, amountDeg: 24, falloff: 1.0, sineFreq: 1.2 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.3, positionX: 0, positionY: 1.15, positionZ: 0 },
      render: { background: '#12141a' },
      camera: shot(6, 58, 30, 0, 1.4, 0),
    },
  },
  {
    name: 'Icon Iso Grid',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.05, thickness: 0.11, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.ISO_GRID,
        isoCountX: 4,
        isoCountZ: 3,
        isoSpacingX: 2.75,
        isoSpacingZ: 3.0,
        isoRowOffset: 0.5,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 6 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: {
        scale: 2.5,
        positionX: 0,
        positionY: 1.31,
        positionZ: 0,
        rotX: 0,
        rotY: 0,
        rotZ: 0,
      },
      render: { background: '#f3f1ec' },
      camera: shot(38, 50, 15.5, 0.7, 1.45, 1.15),
    },
  },
  {
    name: 'Twisted Ring',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.RING,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 9,
        innerRadius: 6.5,
      },
      orientation: { mode: OrientationMode.TANGENT, extraRotX: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.INDEX, amountDeg: 280, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 10 },
      transform: { scale: 1.05 },
      render: { background: '#0b0c10' },
      camera: shot(22, 52, 28, 0, 0.3, 0),
    },
  },
  {
    name: 'Radial Gradient Rotation',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.GRID,
        fillMode: FillMode.FILL,
        countX: 6,
        countZ: 6,
        countY: 1,
        spacingX: 1.22,
        spacingZ: 1.22,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.RADIAL, amountDeg: 360, falloff: 1.8 },
      collision: { mode: CollisionMode.PREVENT, autoIncreaseSpacing: true },
      transform: { scale: 1.15 },
      render: { background: '#111318' },
      camera: shot(18, 38, 16, 0, 0.1, 0),
    },
  },
  {
    name: 'Wave Grid',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.GRID,
        fillMode: FillMode.FILL,
        countX: 6,
        countZ: 6,
        countY: 1,
        spacingX: 1.22,
        spacingZ: 1.22,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'x', source: StaggerSource.SINE, amountDeg: 72, falloff: 1.0, sineFreq: 2.3, sinePhase: 0.0 },
      collision: { mode: CollisionMode.PREVENT, autoIncreaseSpacing: true },
      transform: { scale: 1.15 },
      render: { background: '#0e1218' },
      camera: shot(32, 42, 15.5, 0, 0.15, 0),
    },
  },
  {
    name: 'Sphere Shell',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.SPHERE_SHELL,
        fillMode: FillMode.OUTLINE,
        count: N,
        sphereRadius: 8,
        shellThickness: 0.65,
        jitter: 0.06,
        seed: 7,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.DIST_CENTER, amountDeg: 180, falloff: 2.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 12, cellSize: 1.2 },
      transform: { scale: 1.0 },
      render: { background: '#0a0c10' },
      camera: shot(28, 58, 26, 0, 0.4, 0),
    },
  },
  {
    name: 'Dense Cube',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.CUBE,
        fillMode: FillMode.FILL,
        countX: 3,
        countY: 4,
        countZ: 3,
        spacingX: 1.25,
        spacingY: 1.25,
        spacingZ: 1.25,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.LAYER, amountDeg: 220, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 14, cellSize: 1.0, maxPush: 0.5 },
      transform: { scale: 1.15 },
      render: { background: '#101014' },
      camera: shot(38, 56, 13, 0, 0.2, 0),
    },
  },
  {
    name: 'Spiral Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.SPIRAL,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 5.6,
        height: 7,
        turns: 3.5,
      },
      orientation: { mode: OrientationMode.TANGENT, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.INDEX, amountDeg: 520, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 10, cellSize: 1.1 },
      transform: { scale: 1.1 },
      render: { background: '#0c0e12' },
      camera: shot(48, 68, 20, 0, 0.2, 0),
    },
  },
  {
    name: 'Diamond Grid',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.DIAMOND,
        fillMode: FillMode.FILL,
        countX: 6,
        countZ: 6,
        countY: 1,
        spacingX: 1.22,
        spacingZ: 1.22,
        alternateOffset: true,
        offsetXPerRow: 0.61,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.GRADIENT_X, amountDeg: 160, falloff: 1.2 },
      collision: { mode: CollisionMode.PREVENT, autoIncreaseSpacing: true },
      transform: { scale: 1.1 },
      render: { background: '#12110e' },
      camera: shot(0, 40, 17, 0, 0.1, 0),
    },
  },
  {
    name: 'Helix Tube',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.CYLINDER,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 5.2,
        height: 8,
        turns: 5,
      },
      orientation: { mode: OrientationMode.TANGENT, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.INDEX, amountDeg: 640, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 10, cellSize: 1.1 },
      transform: { scale: 1.05 },
      render: { background: '#0b1012' },
      camera: shot(40, 62, 22, 0, 0.15, 0),
    },
  },
  {
    name: 'Orbital Bands',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.TORUS,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 8,
        innerRadius: 1.85,
        jitter: 0.06,
        seed: 4,
      },
      orientation: { mode: OrientationMode.TANGENT, extraRotX: 90, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.NOISE, amountDeg: 160, falloff: 1.0, noiseScale: 0.15, noiseStrength: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 12, cellSize: 1.2 },
      transform: { scale: 1.0 },
      render: { background: '#0a0b10' },
      camera: shot(18, 54, 26, 0, 0.3, 0),
    },
  },
];

export function listPresetNames() {
  return PRESETS.map((p) => p.name);
}

export function getPresetByName(name) {
  return PRESETS.find((p) => p.name === name) ?? PRESETS[0];
}

export function deepMerge(target, patch) {
  if (patch == null || typeof patch !== 'object') return target;
  for (const [k, v] of Object.entries(patch)) {
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      if (!target[k] || typeof target[k] !== 'object') target[k] = {};
      deepMerge(target[k], v);
    } else {
      target[k] = v;
    }
  }
  return target;
}
