import {
  DistributionType,
  FillMode,
  LoopShape,
  OrientationMode,
  StaggerSource,
  CollisionMode,
} from './state.js';
import { getPresetOverride, getShipped } from './presetDefaults.js';

const N = 36;

function shot(az, pol, dist, x = 0, y = 0, z = 0) {
  return {
    lockFraming: true,
    syncFromOrbit: true,
    azimuthDeg: az,
    polarDeg: pol,
    distance: dist,
    targetX: x,
    targetY: y,
    targetZ: z,
  };
}

export const PRESETS = [
  {
    name: 'Circle Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.CIRCLE,
        count: N,
        loopUseRadius: true,
        radius: 7,
        loopWidth: 7,
        loopDepth: 7,
      },
      orientation: { mode: OrientationMode.TO_CENTER, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.15, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(8, 42, 24, 0, 0.2, 0),
    },
  },
  {
    name: 'Square Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.SQUARE,
        count: N,
        loopUseRadius: false,
        loopWidth: 5.6,
        loopDepth: 5.6,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.2 },
      render: { background: '#000000' },
      camera: shot(28, 48, 22, 0, 0.15, 0),
    },
  },
  {
    name: 'Lozenge Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.DIAMOND,
        count: N,
        loopUseRadius: false,
        loopWidth: 8,
        loopDepth: 8,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.05 },
      render: { background: '#000000' },
      camera: shot(0, 46, 26, 0, 0.2, 0),
    },
  },
  {
    name: 'Hexagon Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.HEXAGON,
        count: N,
        loopUseRadius: false,
        loopWidth: 7.2,
        loopDepth: 7.2,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.1 },
      render: { background: '#000000' },
      camera: shot(0, 44, 24, 0, 0.15, 0),
    },
  },
  {
    name: 'Triangle Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.TRIANGLE,
        count: N,
        loopUseRadius: false,
        loopWidth: 9,
        loopDepth: 9,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.05 },
      render: { background: '#000000' },
      camera: shot(18, 50, 26, 0, 0.2, 0.4),
    },
  },
  {
    name: 'Star Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.STAR,
        count: N,
        loopUseRadius: false,
        loopWidth: 8,
        loopDepth: 8,
        starPoints: 5,
        starInnerRatio: 0.42,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.08 },
      render: { background: '#000000' },
      camera: shot(0, 40, 27, 0, 0.15, 0),
    },
  },
  {
    name: 'Stacked Spiral',
    state: {
      object: { type: 'card' },
      card: {
        width: 1.586,
        height: 1.0,
        thickness: 0.03,
        cornerRadius: 0.06,
        segments: 6,
      },
      distribution: {
        type: DistributionType.COLUMN,
        columnAxis: 'y',
        columnCentered: false,
        columnCount: 30,
        columnSpacing: 0.038,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 260, falloff: 1.0, direction: 1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 5.6, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(34, 66, 16, 0, 3.1, 0.4),
    },
  },
  {
    name: 'Spiral Stack',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.COLUMN,
        columnAxis: 'y',
        columnCentered: false,
        columnCount: 18,
        columnSpacing: 0.16,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 300, falloff: 1.0, direction: 1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 4.5, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(34, 64, 19, 0.3, 6.2, 0.5),
    },
  },
  {
    name: 'Hero Parade',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.1, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 80,
        rowSpacing: 0.5,
        rowAngleDeg: 2.8,
        rowTiltDeg: 0,
        heroIndex: 25,
        heroLift: 0.58,
        heroDetach: 1.12,
        waveAmplitude: 12,
        heroSpacing: 0.68,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 51 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.SINE, amountDeg: 16, falloff: 1.0, sineFreq: 1.1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.15, positionX: 0, positionY: 1.08, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(-32, 64, 26, 4.5, 1.5, 1.2),
    },
  },
  {
    name: 'Iso Breakdown',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.ISO_BREAKDOWN,
        breakdownCount: 9,
        breakdownSpacing: 1.72,
        breakdownAngleDeg: 0,
        breakdownExplode: 0.62,
        breakdownTwistDeg: 28,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.05, positionX: 0, positionY: 1.05, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(45, 54.7, 32, -1.4, 2.35, -0.6),
    },
  },
  {
    name: 'Golden Vortex',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.1, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.GOLDEN_VORTEX,
        vortexCount: 84,
        vortexRadius: 8.6,
        vortexTurns: 3.6,
        vortexScaleIn: 0.1,
        vortexDepth: 2.6,
      },
      orientation: { mode: OrientationMode.SHAPE_NORMAL, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.55, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(22, 34, 31, 0.4, -1.35, 0.3),
    },
  },
  {
    name: 'Frozen Cascade',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.CASCADE,
        cascadeCount: 34,
        cascadeHeight: 15.5,
        cascadeSpread: 2.4,
        cascadeDrift: 1.6,
        seed: 7,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.65, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(62, 80, 24, -0.2, 0.1, 1.6),
    },
  },
  {
    name: 'Grid Glitch',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.11, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.GLITCH_GRID,
        glitchCountX: 11,
        glitchCountZ: 11,
        glitchSpacing: 1.06,
        glitchIndex: 47,
        glitchRotDeg: 52,
        glitchLift: 0.7,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.7, positionX: 0, positionY: 0.85, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(45, 54.7, 14.8, 0, 1.35, 0),
    },
  },
  {
    name: 'Silhouette Pack',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.SILHOUETTE,
        silCount: 500,
        silRadius: 4.6,
        silOverlap: 0.44,
        silPower: 4.2,
        silStack: 0.14,
        seed: 3,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.35, positionX: 0, positionY: 0.08, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(18, 26, 16.5, 0, 0.15, 0),
    },
  },
  {
    name: 'Edge Fan',
    state: {
      object: { type: 'card' },
      card: {
        width: 1.0,
        height: 1.45,
        thickness: 0.035,
        cornerRadius: 0.08,
        segments: 6,
      },
      distribution: {
        type: DistributionType.HAND_FAN,
        fanCount: 14,
        fanRadius: 4.6,
        fanSpreadDeg: 62,
        heroLift: 0,
        heroDetach: 0,
      },
      orientation: { mode: OrientationMode.SHAPE_NORMAL, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.4, positionX: 0, positionY: 1.74, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(-78, 80, 11.5, -1.6, 1.7, 1.4),
    },
  },
  {
    name: 'Domino',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 11,
        rowSpacing: 0.48,
        rowAngleDeg: 8,
        rowTiltDeg: 0,
        heroLift: 0,
        heroDetach: 0,
        heroSpacing: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 8 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 28, falloff: 1.0, direction: 1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.2, positionX: 0, positionY: 1.1, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(-42, 62, 16, -0.4, 1.2, 0.5),
    },
  },
  {
    name: 'Overlap Stair',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.13, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 10,
        rowSpacing: 0.55,
        rowAngleDeg: 18,
        rowTiltDeg: 22,
        heroIndex: 0,
        heroLift: 0,
        heroDetach: 0,
        heroSpacing: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 16 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.25, positionX: 0, positionY: 1.13, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(-28, 54, 17, 0.6, 1.8, 0.8),
    },
  },
  {
    name: 'Layer Stack',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.COLUMN,
        columnAxis: 'y',
        columnCentered: true,
        columnCount: 3,
        columnSpacing: 0.32,
        heroLift: 0,
        heroDetach: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 4.8, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(32, 52, 16, 0.15, 0.15, 0.2),
    },
  },
  {
    name: 'Carousel',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.CAROUSEL,
        carouselCount: 12,
        carouselRadius: 5.2,
        carouselY: 0,
        carouselFaceOut: true,
        carouselRings: 1,
        carouselNested: 1,
        carouselRingPhaseDeg: 0,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.15, positionX: 0, positionY: 1.08, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(34, 50, 32, 0, 1.2, 0),
    },
  },
  {
    name: 'Double Crown',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.13, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.CAROUSEL,
        carouselCount: 10,
        carouselRadius: 4.4,
        carouselY: 0,
        carouselFaceOut: true,
        carouselRings: 2,
        carouselRingSpacing: 2.55,
        carouselRingPhaseDeg: 18,
        carouselNested: 1,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.05, positionX: 0, positionY: 1.03, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(30, 44, 27, 0.2, 2.3, 0.4),
    },
  },
  {
    name: 'Nested Orbits',
    state: {
      object: { type: 'icon' },
      icon: { size: 0.92, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.CAROUSEL,
        carouselCount: 10,
        carouselRadius: 3.4,
        carouselY: 0,
        carouselFaceOut: true,
        carouselRings: 1,
        carouselNested: 2,
        carouselNestedGap: 2.85,
        carouselRingPhaseDeg: 18,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.75, positionX: 0, positionY: 0.88, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(16, 40, 34, 0, 0.95, 0),
    },
  },
  {
    name: 'Look Up',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.CAROUSEL,
        carouselCount: 14,
        carouselRadius: 5.8,
        carouselY: 0,
        carouselFaceOut: true,
        carouselRings: 1,
        carouselNested: 1,
        carouselRingPhaseDeg: 0,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.15, positionX: 0, positionY: 1.08, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(10, 112, 22, 0, 1.2, 0),
    },
  },
  {
    name: 'Cover Flow',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.COVERFLOW,
        coverflowCount: 9,
        coverflowRadius: 7.4,
        coverflowSpreadDeg: 92,
      },
      orientation: { mode: OrientationMode.SHAPE_NORMAL, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.55, positionX: 0, positionY: 1.28, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(0, 68, 18.5, 0, 1.4, 1.2),
    },
  },
  {
    name: 'Fan Deck',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.15, thickness: 0.1, cornerRadius: 0.18, segments: 8 },
      distribution: {
        type: DistributionType.FAN,
        fanCount: 7,
        fanSpacing: 0.78,
        fanDepth: 0.16,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.U, amountDeg: 14, falloff: 1.0 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 3.2, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(6, 58, 20, 0.15, 0.05, 0.6),
    },
  },
  {
    name: 'Diagonal Shelf',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 8,
        rowSpacing: 1.55,
        rowAngleDeg: 28,
        rowTiltDeg: 4,
        heroLift: 0,
        heroDetach: 0,
        heroSpacing: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: -10 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 8, falloff: 1.0 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.7, positionX: 0, positionY: 1.35, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(-38, 48, 24, 0.2, 1.55, 0.4),
    },
  },
  {
    name: 'Wave Parade',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.WAVE_ROW,
        rowCount: 12,
        rowSpacing: 1.5,
        waveAmplitude: 0.55,
        waveLength: 1.1,
        heroLift: 0,
        heroDetach: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.SINE, amountDeg: 16, falloff: 1.0, sineFreq: 1.1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.2, positionX: 0, positionY: 1.1, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(72, 64, 26, 0, 1.4, 0.3),
    },
  },
  {
    name: 'Horizon',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.11, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 9,
        rowSpacing: 2.15,
        rowAngleDeg: 0,
        rowTiltDeg: 0,
        heroLift: 0,
        heroDetach: 0,
        heroSpacing: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 8 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.35, positionX: 0, positionY: 1.18, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(6, 80, 20, 2.4, 1.2, 0.3),
    },
  },
  {
    name: 'Avenue',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.ISO_GRID,
        isoCountX: 2,
        isoCountZ: 8,
        isoSpacingX: 5.4,
        isoSpacingZ: 2.55,
        isoRowOffset: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.1, positionX: 0, positionY: 1.05, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(4, 74, 24, 0, 1.15, 5.8),
    },
  },
  {
    name: 'Iso Grid',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.05, thickness: 0.11, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.ISO_GRID,
        fillMode: FillMode.OUTLINE,
        isoCountX: 4,
        isoCountZ: 3,
        isoSpacingX: 2.75,
        isoSpacingZ: 3.0,
        isoRowOffset: 0.5,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 6 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: {
        scale: 2.5,
        positionX: 0,
        positionY: 1.31,
        positionZ: 0,
        rotX: 0,
        rotY: 0,
        rotZ: 0,
      },
      render: { background: '#000000' },
      camera: shot(15.3, 41.03, 15.5, 0.7, 1.45, 1.15),
    },
  },
  {
    name: 'Low Field',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.ISO_GRID,
        isoCountX: 6,
        isoCountZ: 5,
        isoSpacingX: 3.15,
        isoSpacingZ: 3.45,
        isoRowOffset: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 16 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.95, positionX: 0, positionY: 0.98, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(30, 76, 30, 2.2, 1.1, 7.0),
    },
  },
  {
    name: 'Monument',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.05, thickness: 0.12, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.ISO_GRID,
        isoCountX: 3,
        isoCountZ: 1,
        isoSpacingX: 3.4,
        isoSpacingZ: 3.0,
        isoRowOffset: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 12 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 3.4, positionX: 0, positionY: 1.79, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(36, 68, 22, 0.3, 1.75, 0.8),
    },
  },
  {
    name: 'Twisted Ring',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.RING,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 9,
        innerRadius: 6.5,
      },
      orientation: { mode: OrientationMode.TANGENT, extraRotX: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.INDEX, amountDeg: 280, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 10 },
      transform: { scale: 1.05 },
      render: { background: '#000000' },
      camera: shot(22, 52, 28, 0, 0.3, 0),
    },
  },
  {
    name: 'Radial Rotation',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.GRID,
        fillMode: FillMode.FILL,
        countX: 6,
        countZ: 6,
        countY: 1,
        spacingX: 1.22,
        spacingZ: 1.22,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.RADIAL, amountDeg: 360, falloff: 1.8 },
      collision: { mode: CollisionMode.PREVENT, autoIncreaseSpacing: true },
      transform: { scale: 1.15 },
      render: { background: '#000000' },
      camera: shot(18, 38, 16, 0, 0.1, 0),
    },
  },
  {
    name: 'Wave Grid',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.GRID,
        fillMode: FillMode.FILL,
        countX: 6,
        countZ: 6,
        countY: 1,
        spacingX: 1.22,
        spacingZ: 1.22,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'x', source: StaggerSource.SINE, amountDeg: 72, falloff: 1.0, sineFreq: 2.3, sinePhase: 0.0 },
      collision: { mode: CollisionMode.PREVENT, autoIncreaseSpacing: true },
      transform: { scale: 1.15 },
      render: { background: '#000000' },
      camera: shot(32, 42, 15.5, 0, 0.15, 0),
    },
  },
  {
    name: 'Sphere Shell',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.SPHERE_SHELL,
        fillMode: FillMode.OUTLINE,
        count: N,
        sphereRadius: 8,
        shellThickness: 0.65,
        jitter: 0.06,
        seed: 7,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.DIST_CENTER, amountDeg: 180, falloff: 2.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 12, cellSize: 1.2 },
      transform: { scale: 1.0 },
      render: { background: '#000000' },
      camera: shot(28, 58, 26, 0, 0.4, 0),
    },
  },
  {
    name: 'Dense Cube',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.CUBE,
        fillMode: FillMode.FILL,
        countX: 3,
        countY: 4,
        countZ: 3,
        spacingX: 1.25,
        spacingY: 1.25,
        spacingZ: 1.25,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.LAYER, amountDeg: 220, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 14, cellSize: 1.0, maxPush: 0.5 },
      transform: { scale: 1.15 },
      render: { background: '#000000' },
      camera: shot(38, 56, 13, 0, 0.2, 0),
    },
  },
  {
    name: 'Spiral Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.SPIRAL,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 5.6,
        height: 7,
        turns: 3.5,
      },
      orientation: { mode: OrientationMode.TANGENT, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.INDEX, amountDeg: 520, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 10, cellSize: 1.1 },
      transform: { scale: 1.1 },
      render: { background: '#000000' },
      camera: shot(48, 68, 20, 0, 0.2, 0),
    },
  },
  {
    name: 'Diamond Grid',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.DIAMOND,
        fillMode: FillMode.FILL,
        countX: 6,
        countZ: 6,
        countY: 1,
        spacingX: 1.22,
        spacingZ: 1.22,
        alternateOffset: true,
        offsetXPerRow: 0.61,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.GRADIENT_X, amountDeg: 160, falloff: 1.2 },
      collision: { mode: CollisionMode.PREVENT, autoIncreaseSpacing: true },
      transform: { scale: 1.1 },
      render: { background: '#000000' },
      camera: shot(0, 40, 17, 0, 0.1, 0),
    },
  },
  {
    name: 'Helix Tube',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.CYLINDER,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 5.2,
        height: 8,
        turns: 5,
      },
      orientation: { mode: OrientationMode.TANGENT, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.INDEX, amountDeg: 640, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 10, cellSize: 1.1 },
      transform: { scale: 1.05 },
      render: { background: '#000000' },
      camera: shot(40, 62, 22, 0, 0.15, 0),
    },
  },
  {
    name: 'Orbital Bands',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.TORUS,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 8,
        innerRadius: 1.85,
        jitter: 0.06,
        seed: 4,
      },
      orientation: { mode: OrientationMode.TANGENT, extraRotX: 90, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.NOISE, amountDeg: 160, falloff: 1.0, noiseScale: 0.15, noiseStrength: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 12, cellSize: 1.2 },
      transform: { scale: 1.0 },
      render: { background: '#000000' },
      camera: shot(18, 54, 26, 0, 0.3, 0),
    },
  },
];

const PRESET_ALIASES = {
  'Stacked Card Spiral': 'Stacked Spiral',
  'Icon Spiral Stack': 'Spiral Stack',
  'Icon Hero Parade': 'Hero Parade',
  'Icon Iso Breakdown': 'Iso Breakdown',
  'Icon Golden Vortex': 'Golden Vortex',
  'Icon Frozen Cascade': 'Frozen Cascade',
  'Icon Grid Glitch': 'Grid Glitch',
  'Icon Silhouette Pack': 'Silhouette Pack',
  'Card Edge Fan': 'Edge Fan',
  'Icon Domino': 'Domino',
  'Icon Overlap Stair': 'Overlap Stair',
  'Icon Layer Stack': 'Layer Stack',
  'Icon Carousel': 'Carousel',
  'Icon Double Crown': 'Double Crown',
  'Icon Nested Orbits': 'Nested Orbits',
  'Icon Look Up': 'Look Up',
  'Icon Coverflow': 'Cover Flow',
  'Icon Fan Deck': 'Fan Deck',
  'Icon Diagonal Shelf': 'Diagonal Shelf',
  'Icon Wave Parade': 'Wave Parade',
  'Icon Horizon': 'Horizon',
  'Icon Avenue': 'Avenue',
  'Icon Iso Grid': 'Iso Grid',
  'Icon Low Field': 'Low Field',
  'Icon Monument': 'Monument',
  'Radial Gradient Rotation': 'Radial Rotation',
};

const PRESET_ORDER = [
  'Circle Loop',
  'Square Loop',
  'Lozenge Loop',
  'Hexagon Loop',
  'Triangle Loop',
  'Star Loop',
  'Spiral Loop',
  'Twisted Ring',
  'Helix Tube',
  'Stacked Spiral',
  'Spiral Stack',
  'Golden Vortex',
  'Carousel',
  'Nested Orbits',
  'Orbital Bands',
  'Double Crown',
  'Look Up',
  'Cover Flow',
  'Edge Fan',
  'Fan Deck',
  'Hero Parade',
  'Wave Parade',
  'Diagonal Shelf',
  'Horizon',
  'Avenue',
  'Domino',
  'Overlap Stair',
  'Layer Stack',
  'Iso Grid',
  'Iso Breakdown',
  'Low Field',
  'Monument',
  'Wave Grid',
  'Diamond Grid',
  'Radial Rotation',
  'Grid Glitch',
  'Dense Cube',
  'Frozen Cascade',
  'Silhouette Pack',
  'Sphere Shell',
];

export function canonicalPresetName(name) {
  return PRESET_ALIASES[name] || name;
}

export function listPresetNames() {
  const names = PRESETS.map((p) => p.name);
  const seen = new Set();
  const ordered = [];
  for (const name of PRESET_ORDER) {
    if (names.includes(name) && !seen.has(name)) {
      ordered.push(name);
      seen.add(name);
    }
  }
  for (const name of names) {
    if (!seen.has(name)) ordered.push(name);
  }
  return ordered;
}

export function getPresetByName(name, opts = {}) {
  const key = canonicalPresetName(name);
  const base = PRESETS.find((p) => p.name === key) ?? PRESETS[0];
  const factory = JSON.parse(JSON.stringify(base.state));
  if (opts.factoryOnly) {
    return { name: base.name, state: factory };
  }
  const shipped = getShipped(base.name);
  if (shipped) deepMerge(factory, shipped);
  const override =
    getPresetOverride(base.name) ||
    Object.entries(PRESET_ALIASES)
      .filter(([, neu]) => neu === base.name)
      .map(([old]) => getPresetOverride(old))
      .find(Boolean) ||
    null;
  return {
    name: base.name,
    state: override ? deepMerge(factory, override) : factory,
  };
}

export function deepMerge(target, patch) {
  if (patch == null || typeof patch !== 'object') return target;
  for (const [k, v] of Object.entries(patch)) {
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      if (!target[k] || typeof target[k] !== 'object') target[k] = {};
      deepMerge(target[k], v);
    } else {
      target[k] = v;
    }
  }
  return target;
}
