import {
  DistributionType,
  FillMode,
  LoopShape,
  OrientationMode,
  StaggerSource,
  CollisionMode,
} from './state.js';

const N = 36;

function shot(az, pol, dist, x = 0, y = 0, z = 0) {
  return {
    lockFraming: true,
    syncFromOrbit: true,
    azimuthDeg: az,
    polarDeg: pol,
    distance: dist,
    targetX: x,
    targetY: y,
    targetZ: z,
  };
}

export const PRESETS = [
  {
    name: 'Circle Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.CIRCLE,
        count: N,
        loopUseRadius: true,
        radius: 7,
        loopWidth: 7,
        loopDepth: 7,
      },
      orientation: { mode: OrientationMode.TO_CENTER, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.15, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#0b0c10' },
      camera: shot(8, 42, 24, 0, 0.2, 0),
    },
  },
  {
    name: 'Square Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.SQUARE,
        count: N,
        loopUseRadius: false,
        loopWidth: 5.6,
        loopDepth: 5.6,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.2 },
      render: { background: '#101218' },
      camera: shot(28, 48, 22, 0, 0.15, 0),
    },
  },
  {
    name: 'Lozenge Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.DIAMOND,
        count: N,
        loopUseRadius: false,
        loopWidth: 8,
        loopDepth: 8,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.05 },
      render: { background: '#0c1014' },
      camera: shot(0, 46, 26, 0, 0.2, 0),
    },
  },
  {
    name: 'Hexagon Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.HEXAGON,
        count: N,
        loopUseRadius: false,
        loopWidth: 7.2,
        loopDepth: 7.2,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.1 },
      render: { background: '#0e1210' },
      camera: shot(0, 44, 24, 0, 0.15, 0),
    },
  },
  {
    name: 'Triangle Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.TRIANGLE,
        count: N,
        loopUseRadius: false,
        loopWidth: 9,
        loopDepth: 9,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.05 },
      render: { background: '#120e10' },
      camera: shot(18, 50, 26, 0, 0.2, 0.4),
    },
  },
  {
    name: 'Star Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.LOOP,
        fillMode: FillMode.OUTLINE,
        loopShape: LoopShape.STAR,
        count: N,
        loopUseRadius: false,
        loopWidth: 8,
        loopDepth: 8,
        starPoints: 5,
        starInnerRatio: 0.42,
      },
      orientation: { mode: OrientationMode.TO_CENTER, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.08 },
      render: { background: '#0d0b12' },
      camera: shot(0, 40, 27, 0, 0.15, 0),
    },
  },
  {
    name: 'Stacked Card Spiral',
    state: {
      object: { type: 'card' },
      card: {
        width: 1.586,
        height: 1.0,
        thickness: 0.03,
        cornerRadius: 0.06,
        segments: 6,
      },
      distribution: {
        type: DistributionType.COLUMN,
        columnAxis: 'y',
        columnCentered: false,
        columnCount: 30,
        columnSpacing: 0.038,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 260, falloff: 1.0, direction: 1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 5.6, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#0b0c10' },
      camera: shot(34, 66, 16, 0, 3.1, 0.4),
    },
  },
  {
    name: 'Icon Spiral Stack',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.COLUMN,
        columnAxis: 'y',
        columnCentered: false,
        columnCount: 18,
        columnSpacing: 0.16,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 300, falloff: 1.0, direction: 1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 4.5, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#f4f4f5' },
      camera: shot(34, 64, 19, 0.3, 6.2, 0.5),
    },
  },
  {
    name: 'Icon Hero Parade',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.16, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 13,
        rowSpacing: 0.42,
        rowAngleDeg: 0,
        rowTiltDeg: 0,
        heroIndex: 6,
        heroLift: 0.92,
        waveAmplitude: 4.2,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 22 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.15, positionX: 0, positionY: 1.08, positionZ: 0 },
      render: { background: '#c9d8f0' },
      camera: shot(-36, 58, 15.5, -0.8, 1.55, 0.35),
    },
  },
  {
    name: 'Card Edge Fan',
    state: {
      object: { type: 'card' },
      card: {
        width: 1.0,
        height: 1.45,
        thickness: 0.035,
        cornerRadius: 0.08,
        segments: 6,
      },
      distribution: {
        type: DistributionType.HAND_FAN,
        fanCount: 14,
        fanRadius: 4.6,
        fanSpreadDeg: 62,
        heroLift: 0,
      },
      orientation: { mode: OrientationMode.SHAPE_NORMAL, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.4, positionX: 0, positionY: 1.74, positionZ: 0 },
      render: { background: '#0a0a0c' },
      camera: shot(-78, 80, 11.5, -1.6, 1.7, 1.4),
    },
  },
  {
    name: 'Icon Domino',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 11,
        rowSpacing: 0.48,
        rowAngleDeg: 8,
        rowTiltDeg: 0,
        heroLift: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 8 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 28, falloff: 1.0, direction: 1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.2, positionX: 0, positionY: 1.1, positionZ: 0 },
      render: { background: '#ece7de' },
      camera: shot(-42, 62, 16, -0.4, 1.2, 0.5),
    },
  },
  {
    name: 'Icon Overlap Stair',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.13, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 10,
        rowSpacing: 0.55,
        rowAngleDeg: 18,
        rowTiltDeg: 22,
        heroIndex: 0,
        heroLift: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 16 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.25, positionX: 0, positionY: 1.13, positionZ: 0 },
      render: { background: '#dfe6f2' },
      camera: shot(-28, 54, 17, 0.6, 1.8, 0.8),
    },
  },
  {
    name: 'Icon Layer Stack',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.COLUMN,
        columnAxis: 'y',
        columnCentered: true,
        columnCount: 3,
        columnSpacing: 0.32,
        heroLift: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 0, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 4.8, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#ffffff' },
      camera: shot(32, 52, 16, 0.15, 0.15, 0.2),
    },
  },
  {
    name: 'Icon Carousel',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.CAROUSEL,
        carouselCount: 12,
        carouselRadius: 5.2,
        carouselY: 0,
        carouselFaceOut: true,
        carouselRings: 1,
        carouselNested: 1,
        carouselRingPhaseDeg: 0,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.15, positionX: 0, positionY: 1.08, positionZ: 0 },
      render: { background: '#0c0d10' },
      camera: shot(34, 50, 32, 0, 1.2, 0),
    },
  },
  {
    name: 'Icon Double Crown',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.13, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.CAROUSEL,
        carouselCount: 10,
        carouselRadius: 4.4,
        carouselY: 0,
        carouselFaceOut: true,
        carouselRings: 2,
        carouselRingSpacing: 2.55,
        carouselRingPhaseDeg: 18,
        carouselNested: 1,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.05, positionX: 0, positionY: 1.03, positionZ: 0 },
      render: { background: '#000000' },
      camera: shot(30, 44, 27, 0.2, 2.3, 0.4),
    },
  },
  {
    name: 'Icon Nested Orbits',
    state: {
      object: { type: 'icon' },
      icon: { size: 0.92, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.CAROUSEL,
        carouselCount: 10,
        carouselRadius: 3.4,
        carouselY: 0,
        carouselFaceOut: true,
        carouselRings: 1,
        carouselNested: 2,
        carouselNestedGap: 2.85,
        carouselRingPhaseDeg: 18,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.75, positionX: 0, positionY: 0.88, positionZ: 0 },
      render: { background: '#111318' },
      camera: shot(16, 40, 34, 0, 0.95, 0),
    },
  },
  {
    name: 'Icon Look Up',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.14, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.CAROUSEL,
        carouselCount: 14,
        carouselRadius: 5.8,
        carouselY: 0,
        carouselFaceOut: true,
        carouselRings: 1,
        carouselNested: 1,
        carouselRingPhaseDeg: 0,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.15, positionX: 0, positionY: 1.08, positionZ: 0 },
      render: { background: '#0a0b0e' },
      camera: shot(10, 112, 22, 0, 1.2, 0),
    },
  },
  {
    name: 'Icon Coverflow',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.COVERFLOW,
        coverflowCount: 9,
        coverflowRadius: 7.4,
        coverflowSpreadDeg: 92,
      },
      orientation: { mode: OrientationMode.SHAPE_NORMAL, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.55, positionX: 0, positionY: 1.28, positionZ: 0 },
      render: { background: '#e7edf6' },
      camera: shot(0, 68, 18.5, 0, 1.4, 1.2),
    },
  },
  {
    name: 'Icon Fan Deck',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.15, thickness: 0.1, cornerRadius: 0.18, segments: 8 },
      distribution: {
        type: DistributionType.FAN,
        fanCount: 7,
        fanSpacing: 0.78,
        fanDepth: 0.16,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.U, amountDeg: 14, falloff: 1.0 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 3.2, positionX: 0, positionY: 0, positionZ: 0 },
      render: { background: '#8d8d8d' },
      camera: shot(6, 58, 20, 0.15, 0.05, 0.6),
    },
  },
  {
    name: 'Icon Diagonal Shelf',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 8,
        rowSpacing: 1.55,
        rowAngleDeg: 28,
        rowTiltDeg: 4,
        heroLift: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: -10 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.U, amountDeg: 8, falloff: 1.0 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.7, positionX: 0, positionY: 1.35, positionZ: 0 },
      render: { background: '#d8e0ee' },
      camera: shot(-38, 48, 24, 0.2, 1.55, 0.4),
    },
  },
  {
    name: 'Icon Wave Parade',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.22, segments: 8 },
      distribution: {
        type: DistributionType.WAVE_ROW,
        rowCount: 12,
        rowSpacing: 1.5,
        waveAmplitude: 0.55,
        waveLength: 1.1,
        heroLift: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.SINE, amountDeg: 16, falloff: 1.0, sineFreq: 1.1 },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.2, positionX: 0, positionY: 1.1, positionZ: 0 },
      render: { background: '#101218' },
      camera: shot(72, 64, 26, 0, 1.4, 0.3),
    },
  },
  {
    name: 'Icon Horizon',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.11, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.DIAGONAL_ROW,
        rowCount: 9,
        rowSpacing: 2.15,
        rowAngleDeg: 0,
        rowTiltDeg: 0,
        heroLift: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 8 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.35, positionX: 0, positionY: 1.18, positionZ: 0 },
      render: { background: '#f2efe8' },
      camera: shot(6, 80, 20, 2.4, 1.2, 0.3),
    },
  },
  {
    name: 'Icon Avenue',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.ISO_GRID,
        isoCountX: 2,
        isoCountZ: 8,
        isoSpacingX: 5.4,
        isoSpacingZ: 2.55,
        isoRowOffset: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 0 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 2.1, positionX: 0, positionY: 1.05, positionZ: 0 },
      render: { background: '#ece8e1' },
      camera: shot(4, 74, 24, 0, 1.15, 5.8),
    },
  },
  {
    name: 'Icon Iso Grid',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.05, thickness: 0.11, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.ISO_GRID,
        isoCountX: 4,
        isoCountZ: 3,
        isoSpacingX: 2.75,
        isoSpacingZ: 3.0,
        isoRowOffset: 0.5,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 6 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: {
        scale: 2.5,
        positionX: 0,
        positionY: 1.31,
        positionZ: 0,
        rotX: 0,
        rotY: 0,
        rotZ: 0,
      },
      render: { background: '#f3f1ec' },
      camera: shot(38, 50, 15.5, 0.7, 1.45, 1.15),
    },
  },
  {
    name: 'Icon Low Field',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.0, thickness: 0.12, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.ISO_GRID,
        isoCountX: 6,
        isoCountZ: 5,
        isoSpacingX: 3.15,
        isoSpacingZ: 3.45,
        isoRowOffset: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 16 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 1.95, positionX: 0, positionY: 0.98, positionZ: 0 },
      render: { background: '#f4f2ed' },
      camera: shot(30, 76, 30, 2.2, 1.1, 7.0),
    },
  },
  {
    name: 'Icon Monument',
    state: {
      object: { type: 'icon' },
      icon: { size: 1.05, thickness: 0.12, cornerRadius: 0.2, segments: 8 },
      distribution: {
        type: DistributionType.ISO_GRID,
        isoCountX: 3,
        isoCountZ: 1,
        isoSpacingX: 3.4,
        isoSpacingZ: 3.0,
        isoRowOffset: 0,
      },
      orientation: { mode: OrientationMode.FIXED, extraRotX: 90, extraRotY: 0, extraRotZ: 0, yawDeg: 12 },
      stagger: { enabled: false },
      collision: { mode: CollisionMode.OFF },
      transform: { scale: 3.4, positionX: 0, positionY: 1.79, positionZ: 0 },
      render: { background: '#eae6de' },
      camera: shot(36, 68, 22, 0.3, 1.75, 0.8),
    },
  },
  {
    name: 'Twisted Ring',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.RING,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 9,
        innerRadius: 6.5,
      },
      orientation: { mode: OrientationMode.TANGENT, extraRotX: 0, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.INDEX, amountDeg: 280, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 10 },
      transform: { scale: 1.05 },
      render: { background: '#0b0c10' },
      camera: shot(22, 52, 28, 0, 0.3, 0),
    },
  },
  {
    name: 'Radial Gradient Rotation',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.GRID,
        fillMode: FillMode.FILL,
        countX: 6,
        countZ: 6,
        countY: 1,
        spacingX: 1.22,
        spacingZ: 1.22,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.RADIAL, amountDeg: 360, falloff: 1.8 },
      collision: { mode: CollisionMode.PREVENT, autoIncreaseSpacing: true },
      transform: { scale: 1.15 },
      render: { background: '#111318' },
      camera: shot(18, 38, 16, 0, 0.1, 0),
    },
  },
  {
    name: 'Wave Grid',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.GRID,
        fillMode: FillMode.FILL,
        countX: 6,
        countZ: 6,
        countY: 1,
        spacingX: 1.22,
        spacingZ: 1.22,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'x', source: StaggerSource.SINE, amountDeg: 72, falloff: 1.0, sineFreq: 2.3, sinePhase: 0.0 },
      collision: { mode: CollisionMode.PREVENT, autoIncreaseSpacing: true },
      transform: { scale: 1.15 },
      render: { background: '#0e1218' },
      camera: shot(32, 42, 15.5, 0, 0.15, 0),
    },
  },
  {
    name: 'Sphere Shell',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.SPHERE_SHELL,
        fillMode: FillMode.OUTLINE,
        count: N,
        sphereRadius: 8,
        shellThickness: 0.65,
        jitter: 0.06,
        seed: 7,
      },
      orientation: { mode: OrientationMode.OUT_FROM_CENTER, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.DIST_CENTER, amountDeg: 180, falloff: 2.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 12, cellSize: 1.2 },
      transform: { scale: 1.0 },
      render: { background: '#0a0c10' },
      camera: shot(28, 58, 26, 0, 0.4, 0),
    },
  },
  {
    name: 'Dense Cube',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.CUBE,
        fillMode: FillMode.FILL,
        countX: 3,
        countY: 4,
        countZ: 3,
        spacingX: 1.25,
        spacingY: 1.25,
        spacingZ: 1.25,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.LAYER, amountDeg: 220, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 14, cellSize: 1.0, maxPush: 0.5 },
      transform: { scale: 1.15 },
      render: { background: '#101014' },
      camera: shot(38, 56, 13, 0, 0.2, 0),
    },
  },
  {
    name: 'Spiral Loop',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.SPIRAL,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 5.6,
        height: 7,
        turns: 3.5,
      },
      orientation: { mode: OrientationMode.TANGENT, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.INDEX, amountDeg: 520, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 10, cellSize: 1.1 },
      transform: { scale: 1.1 },
      render: { background: '#0c0e12' },
      camera: shot(48, 68, 20, 0, 0.2, 0),
    },
  },
  {
    name: 'Diamond Grid',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.DIAMOND,
        fillMode: FillMode.FILL,
        countX: 6,
        countZ: 6,
        countY: 1,
        spacingX: 1.22,
        spacingZ: 1.22,
        alternateOffset: true,
        offsetXPerRow: 0.61,
      },
      orientation: { mode: OrientationMode.FIXED, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.GRADIENT_X, amountDeg: 160, falloff: 1.2 },
      collision: { mode: CollisionMode.PREVENT, autoIncreaseSpacing: true },
      transform: { scale: 1.1 },
      render: { background: '#12110e' },
      camera: shot(0, 40, 17, 0, 0.1, 0),
    },
  },
  {
    name: 'Helix Tube',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.CYLINDER,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 5.2,
        height: 8,
        turns: 5,
      },
      orientation: { mode: OrientationMode.TANGENT, yawDeg: 0 },
      stagger: { enabled: true, axis: 'y', source: StaggerSource.INDEX, amountDeg: 640, falloff: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 10, cellSize: 1.1 },
      transform: { scale: 1.05 },
      render: { background: '#0b1012' },
      camera: shot(40, 62, 22, 0, 0.15, 0),
    },
  },
  {
    name: 'Orbital Bands',
    state: {
      object: { type: 'coin' },
      distribution: {
        type: DistributionType.TORUS,
        fillMode: FillMode.OUTLINE,
        count: N,
        radius: 8,
        innerRadius: 1.85,
        jitter: 0.06,
        seed: 4,
      },
      orientation: { mode: OrientationMode.TANGENT, extraRotX: 90, yawDeg: 0 },
      stagger: { enabled: true, axis: 'z', source: StaggerSource.NOISE, amountDeg: 160, falloff: 1.0, noiseScale: 0.15, noiseStrength: 1.0 },
      collision: { mode: CollisionMode.RESOLVE, iterations: 12, cellSize: 1.2 },
      transform: { scale: 1.0 },
      render: { background: '#0a0b10' },
      camera: shot(18, 54, 26, 0, 0.3, 0),
    },
  },
];

export function listPresetNames() {
  return PRESETS.map((p) => p.name);
}

export function getPresetByName(name) {
  return PRESETS.find((p) => p.name === name) ?? PRESETS[0];
}

export function deepMerge(target, patch) {
  if (patch == null || typeof patch !== 'object') return target;
  for (const [k, v] of Object.entries(patch)) {
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      if (!target[k] || typeof target[k] !== 'object') target[k] = {};
      deepMerge(target[k], v);
    } else {
      target[k] = v;
    }
  }
  return target;
}
